import Head from "next/head";
import Hero from "../components/marketing/Hero";
import Wizard from "components/wizard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Junk-drawr | Put your junk in a box</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/box.png" />
      </Head>

      <main>
        <Hero
          title="Put your junk in a box"
          subTitle="Responsibly get rid of your junk drawer."
        />
        <Wizard />
      </main>
    </div>
  );
}
