import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../components/marketing/Hero";
import FeaturesSection from "components/marketing/FeaturesSection";
import Wizard from "components/wizard";

const howItems = [
  {
    title: "Put your junk in a box",
    body: "Grab that old ecommerce box you've got lying around and give me your e-waste, hard to recycle items, and junk you just don't know how to deal with.",
    image: "https://uploads.divjoy.com/undraw-fish_bowl_uu88.svg",
    width: 400,
    height: 400,
  },
  {
    title: "Print off your shipping label",
    body: "Tell us about the box, follow some simple rules to make everything safe, and then pay for your shipping label.We'll email it to you along with some simple instructions.",
    image: "https://uploads.divjoy.com/undraw-directions_x53j.svg",
    width: 400,
    height: 400,
  },
  {
    title: "Mail us that box",
    body: "Afix the shipping labels and throw it in the mail at your leisure!",
    image: "https://uploads.divjoy.com/undraw-stability_ball_b4ia.svg",
    width: 400,
    height: 400,
  },
  {
    title: "We donate, upcycle, and recycle",
    body: "We'll make sure everything gets appropriately donated, upcycled, and recycled at responsible recycling centers in the U.S.",
    image: "https://uploads.divjoy.com/undraw-personal_settings_kihd.svg",
    width: 400,
    height: 400,
  },
  {
    title: "Get a pat on the back",
    body: " We’ll send you some coupons and discounts you can use at leading retailers to make all this worth it! Thanks for putting your junk in a box!",
    image: "https://uploads.divjoy.com/undraw-personal_settings_kihd.svg",
    width: 400,
    height: 400,
  },
];

const whyItems = [
  {
    title: "It's better for the environment",
    body: "Electronics sent to the landfill can leak toxins into the soil and at times the water supply. ",
    image: "https://uploads.divjoy.com/undraw-fish_bowl_uu88.svg",
    width: 400,
    height: 400,
  },
  {
    title: "E-waste contains valuable resources for the economy",
    body: "Lithium, nickel, cobalt, gold, silver, and carbon can all be found in modern e-waste. These materials are critical ",
    image: "https://uploads.divjoy.com/undraw-directions_x53j.svg",
    width: 400,
    height: 400,
  },
  {
    title: "It's circular",
    body: "Recyclying more e-waste means less minerals need to be mined and processed.",
    image: "https://uploads.divjoy.com/undraw-stability_ball_b4ia.svg",
    width: 400,
    height: 400,
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Junk-drawr | Put your junk in a box</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/box.png" />
      </Head>

      <main>
        <Hero
          title="Put your junk in a box"
          subTitle="Responsibly get rid of your junk drawer."
        />
        <Wizard />
        {/* <FeaturesSection
          bgColor="#a1c181"
          items={howItems}
          title="HOW IT WORKS"
          subtitle="If it doesn't give your joy, give it to me."
        />
        <FeaturesSection
          bgColor="#a1c181"
          items={whyItems}
          title="WHY RECYCLE"
          //subtitle="If it doesn't give your joy, give it to me."
        /> */}
      </main>
    </div>
  );
}
